########################################
#  extract_subtable_output_summaries.R
########################################
# 
# author = Alberto Pascual-García 
# email = alberto.pascual.garcia@gmail.com 
# date = 29th July 2020
# description = This function extracts a subset of Ncomp experiments to be compared from the
#   whole table of output summaries (generated by model_output_summaries.R)
#
# requires = Number of experiments (Ncomp), table with experiments (df.out), data frame with
#  the parameters to identify the experiments (params.df)
#
extract_subtable_output_summaries = function(Ncomp,df.out,params.df){
  #browser()
  df.sub=data.frame()
  for(i in 1:Ncomp){
    contacts.var=as.character(params.df$contacts[i])
    PopSize.var=paste("PopSize",params.df$Npop[i],sep="")
    Isolate.var=paste("Isolate",params.df$Isolate[i],sep="")
    Limit.var=paste("Limit",params.df$Limit[i],sep="")
    Onset.var=paste("Onset",params.df$Onset[i],sep="")
    Fate.var=paste("Fate",params.df$Fate[i],sep="")
    Tcheck.var=paste("Tcheck",params.df$Tcheck[i],sep="")
    lock.var=paste("lock",params.df$lock[i],sep="")
    self.var=paste("self",params.df$self[i],sep="")
    
    df.tmp=subset(df.out, contacts==contacts.var &  Isolate==Isolate.var & 
                    Onset == Onset.var & Limit==Limit.var & Fate==Fate.var & Tcheck==Tcheck.var &
                    PopSize==PopSize.var & lock==lock.var & self==self.var)
    if(dim(df.tmp)[1]==0){warning(paste("File in line",i,"of the input file not found"))}
    
    df.sub=rbind(df.sub,df.tmp)
  }
  return(df.sub)
}
