# ****************************************
# model_output_summaries_plotMaster.R
# ****************************************
# 
# 
# author = Alberto Pascual-García 
# email = alberto.pascual.garcia@gmail.com 
# date = 30th July 2020
# description = This function plots as many figures as variables defined in vars.lists, that are  
#   variables contained in Summary_interventions_$label.csv, generated by model_output_summaries.R. 
#   The function is called from model_output_summaries_plotMaster.R as many times as experiments
#   are considered, where each experiment is a combination of simulations whose aesthetics and
#   descriptions are previously defined, and passed to this function in the list "experiment".
#   See those scripts for further details.
#
#

model_output_summaries_plotSingle = function(experiment,dirCode,dirPlotOut){
  
  setwd(dirCode) # needed to load the table with the set of simulations 
  
  # --- Retrieve description of the experiment
  # .... df
  df.exp=experiment[[1]]
  fileIn=as.character(df.exp$fileIn)
  title.lab=as.character(df.exp$title.lab)
  subtitle.lab=as.character(df.exp$subtitle.lab)
  varX=as.character(df.exp$varX)
  xlabel.lab=as.character(df.exp$xlabel.lab)
  plot.type=as.character(df.exp$plot.type)
  pdf.width=df.exp$pdf.width
  pdf.height=df.exp$pdf.height
  
  # .... vector of labels for the scale
  scale.manual.lab=experiment[[2]]
  n.scale=length(scale.manual.lab) # inspect  the scale manual labs
  tot.chars=nchar(scale.manual.lab[n.scale]) # if the last element has more than 5 chars (typically the longest)
  angle.lab=0
  hjust.lab=0.5
  if(tot.chars>4){ # you probably need to rotate the labs
    angle.lab=45
    hjust.lab=1
  }
  cat(">> Plotting results from experiment: ",fileIn,"\n")
  
  # --- Read the interventions
  params.df=read.table(file=fileIn,header = TRUE,sep=",") 
  Ncomp=dim(params.df)[1] 
  
  # ... convert into df to subset
  df.out=df.output # just preventive as.data.frame(df.output,stringsAsFactors = FALSE)
  
  # --- Subset table
  df.sub = extract_subtable_output_summaries(Ncomp,df.out,params.df)
  
  dim(df.sub)
  intervention=as.factor(seq(from=1,to=dim(df.sub)[1],by=1))
  df.sub=cbind(intervention,df.sub)
  
  # --- List of plots that will be defined
  vars.list=list()
  vars.list[[1]]=data.frame(varY="NumFinalDeaths.mean", 
                            errY="NumFinalDeaths.stderr",
                            ylabel="Fraction of population dying")
  vars.list[[2]]=data.frame(varY="TimePeakSymptomatic.mean",
                            errY="TimePeakSymptomatic.stderr",
                            ylabel="Time to peak of symptomatic (days)")
  vars.list[[3]]=data.frame(varY="NumFinalRecovered.mean",
                            errY="NumFinalRecovered.stderr",
                            ylabel="Fraction of population recovered")
  vars.list[[4]]=data.frame(varY="CFR.E",
                            ylabel="Case Fatality Rate")
  vars.list[[5]]=data.frame(varY="P.outbrk.E",
                            ylabel="Probability of outbreak")
  
  # --- Redefine varX, initialize  and plot
  setwd(dirPlotOut)
  varX.out=varX # we will use it just for output files
  varX="intervention" # and we will use as X simply the index, and set the labels manually
  i=0
  for(var.list.local in vars.list){
    i=i+1
    # ... Retrieve te var to plot and its labels
    df.vars=vars.list[[i]]
    varY=as.character(df.vars$varY)
    ylabel=as.character(df.vars$ylabel)
    # ... set the output file
    filePlotOut=paste(varX.out,"Vs",varY,".pdf",sep="")
    # ... prepare the main plot
    gg=ggplot(data = df.sub) +  # assign columns to axes and groups
      geom_point(aes_string(x = varX, y = varY),size=2)+
      geom_line(aes_string(x = varX, y = varY,group=1),color="red")
    # ... add error bars if needed
    if(!((varY=="P.outbrk.E")||(varY=="CFR.E"))){ # error bars needed
      errY=as.character(df.vars$errY)
      errX=df.sub[,varX]
      errMin=df.sub[,varY]-df.sub[,errY]
      errMax=df.sub[,varY]+df.sub[,errY]
      gg=gg+geom_errorbar(aes(x=errX,ymin=errMin, ymax=errMax), width=.1)
    }
    # ... rest of aesthetics
    gg=gg+
      xlab(xlabel.lab)+           # add label for x axis
      ylab(ylabel) +     # add label for y axis
      theme_bw()+
      theme(axis.title = element_text(size=22),
            axis.text.y = element_text(size=20),
            axis.text.x = element_text(size=20, angle=angle.lab, hjust = hjust.lab,vjust=1),
            legend.text = element_text(size=22),
            legend.title = element_text(size=28),
            title=element_text(size=16))+ # Increase fonts size
      #scale_colour_manual(values=col_qual)+
      scale_x_discrete(labels=scale.manual.lab)+
      labs(title = title.lab,
           subtitle = subtitle.lab)
    pdf(file=filePlotOut,width=pdf.width,height = pdf.height)
    print(gg)
    dev.off( )
  }
  
}
