# ****************************************
# model_output_summaries_plotDouble.R
# ****************************************
# 
# 
# author = Alberto Pascual-García 
# email = alberto.pascual.garcia@gmail.com 
# date = 30th July 2020
# description = This function plots as many figures as variables defined in vars.lists, that are  
#   variables contained in Summary_interventions_$label.csv, generated by model_output_summaries.R. 
#   The function is called from model_output_summaries_plotMaster.R as many times as experiments
#   are considered, where each experiment is a combination of simulations whose aesthetics and
#   descriptions are previously defined, and passed to this function in the list "experiment".
#   See those scripts for further details.
#   While the "Single" version plots only the totals of all the population, this script can create
#   plots differentiating the "shielded" (a.k.a isolated in safety zone) and "exposed" populations.


model_output_summaries_plotDouble = function(df.output,experiment,dirCode,dirPlotOut){
  
  setwd(dirCode) # needed to load the table with the set of simulations 
  
  # --- Retrieve description of the experiment
  # .... df
  df.exp=experiment[[1]]
  fileIn=as.character(df.exp$fileIn)
  title.lab=as.character(df.exp$title.lab)
  subtitle.lab=as.character(df.exp$subtitle.lab)
  varX=as.character(df.exp$varX)
  xlabel.lab=as.character(df.exp$xlabel.lab)
  plot.type=as.character(df.exp$plot.type)
  pdf.width=df.exp$pdf.width
  pdf.height=df.exp$pdf.height
  
  # .... vector of labels and colors
  # ...... named colors for the legend
  values.lab =c("black","orange","green")
  names(values.lab)=c("total","exposed zone","safety zone")
  # ...... labels for the scale
  scale.manual.lab=experiment[[2]]
  n.scale=length(scale.manual.lab) # inspect  the scale manual labs
  tot.chars=nchar(scale.manual.lab[n.scale]) # if the last element has more than 5 chars (typically the longest)
  angle.lab=0
  hjust.lab=0.5
  if(tot.chars>4){ # you probably need to rotate the labs
    angle.lab=45
    hjust.lab=1
  }
  cat(">> Plotting results from experiment: ",fileIn,"\n")
  
  # --- Read the interventions
  params.df=read.table(file=fileIn,header = TRUE,sep=",") 
  Ncomp=dim(params.df)[1] 
  
  # ... convert into df to subset
  df.out=df.output # just preventive as.data.frame(df.output,stringsAsFactors = FALSE)
  
  # --- Subset table
  df.sub = extract_subtable_output_summaries(Ncomp,df.out,params.df)
  
  dim(df.sub)
  intervention=as.factor(seq(from=1,to=dim(df.sub)[1],by=1))
  df.sub=cbind(intervention,df.sub)
  
  # --- List of plots that will be defined
  vars.list=list()
  vars.list[[1]]=data.frame(varY0="NumFinalDeaths.mean", 
                            errY0="NumFinalDeaths.stderr",
                            varY1="NumFinalDeaths.mean.E", 
                            errY1="NumFinalDeaths.stderr.E",
                            varY2="NumFinalDeaths.mean.S", 
                            errY2="NumFinalDeaths.stderr.S",
                            ylabel="Fraction of population dying")
  vars.list[[2]]=data.frame(varY0="TimePeakSymptomatic.mean",
                            errY0="TimePeakSymptomatic.stderr",
                            varY1="TimePeakSymptomatic.mean.E",
                            errY1="TimePeakSymptomatic.stderr.E",
                            varY2="TimePeakSymptomatic.mean.S",
                            errY2="TimePeakSymptomatic.stderr.S",
                            ylabel="Time to peak of symptomatic (days)")
  vars.list[[3]]=data.frame(varY0="NumFinalRecovered.mean",
                            errY0="NumFinalRecovered.stderr",
                            varY1="NumFinalRecovered.mean.E",
                            errY1="NumFinalRecovered.stderr.E",
                            varY2="NumFinalRecovered.mean.S",
                            errY2="NumFinalRecovered.stderr.S",
                            ylabel="Fraction of population recovered")
  vars.list[[4]]=data.frame(varY0="CFR",
                            varY1="CFR.E",
                            varY2="CFR.S",
                            ylabel="Case Fatality Rate")
  vars.list[[5]]=data.frame(varY0="P.outbrk",
                            varY1="P.outbrk.E",
                            varY2="P.outbrk.S",
                            ylabel="Probability of outbreak")
  
  # --- Redefine varX, initialize  and plot
  setwd(dirPlotOut)
  varX.out=varX # we will use it just for output files
  varX.char="intervention" # and we will use as X simply the index, and set the labels manually
  i=0
  for(var.list.local in vars.list){
    i=i+1
    # ... Retrieve te var to plot and its labels
    df.vars=vars.list[[i]]
    varY0.char=as.character(df.vars$varY0)
    varY1.char=as.character(df.vars$varY1)
    varY2.char=as.character(df.vars$varY2)
    varX=df.sub[,varX.char]
    varY0=df.sub[,varY0.char]
    varY1=df.sub[,varY1.char] # This is needed because I am unable to use aes_string with colour="string", as I
    varY2=df.sub[,varY2.char] #"`P.outbrk.E`"
    ylabel=as.character(df.vars$ylabel)
    # ... set the output file
    filePlotOut=paste(varX.out,"Vs",varY0.char,"_byClass.pdf",sep="")
    #filePlotOut=paste(varX.out,"Vs",varY0.char,"_byClass_unlabelled.pdf",sep="")
    
    # ... prepare the main plot
    gg=ggplot(data = df.sub) +  # assign columns to axes and groups
      geom_point(aes(x = varX, y = varY0, colour="total"),size=2)+
      geom_line(aes(x = varX, y = varY0, colour = "total", group=1))+
      geom_point(aes(x = varX, y = varY1, colour="exposed zone"),size=2)+
      geom_line(aes(x = varX, y = varY1, colour = "exposed zone", group=1))+
      geom_point(aes(x = varX, y = varY2,colour ="safety zone"),size=2)+
      geom_line(aes(x = varX, y = varY2, colour = "safety zone", group=1),show.legend = TRUE)
    # ... add error bars if needed
    if(!((varY1.char=="P.outbrk.E")||(varY1.char=="CFR.E"))){ # error bars needed
      errY0.char=as.character(df.vars$errY0)
      errY1.char=as.character(df.vars$errY1)
      errY2.char=as.character(df.vars$errY2)
      errX=varX
      errMin0=df.sub[,varY0.char]-df.sub[,errY0.char]
      errMax0=df.sub[,varY0.char]+df.sub[,errY0.char]
      errMin1=df.sub[,varY1.char]-df.sub[,errY1.char]
      errMax1=df.sub[,varY1.char]+df.sub[,errY1.char]
      errMin2=df.sub[,varY2.char]-df.sub[,errY2.char]
      errMax2=df.sub[,varY2.char]+df.sub[,errY2.char]
      gg=gg+geom_errorbar(aes(x=errX,ymin=errMin0, ymax=errMax0,colour="total"), width=.1)+
        geom_errorbar(aes(x=errX,ymin=errMin1, ymax=errMax1,colour="exposed zone"), width=.1)+
        geom_errorbar(aes(x=errX,ymin=errMin2, ymax=errMax2,colour="safety zone"), width=.1)
    }
    # ... rest of aesthetics
    gg=gg+scale_color_manual("",
                             breaks=c("total","exposed zone","safety zone"),
                             values = values.lab)+
      #geom_bar(stat="identity") +                  # represent data as lines
      xlab(xlabel.lab)+           # add label for x axis
      ylab(ylabel) +     # add label for y axis
      theme_bw()+
      theme(axis.title = element_text(size=22),
            axis.text.x = element_text(size=18,angle = angle.lab,hjust=hjust.lab,vjust = 1),
            axis.text.y = element_text(size=20),
            legend.text = element_text(size=22),
            legend.title = element_text(size=28),
            title=element_text(size=16))+ # Increase fonts size
      #scale_colour_manual(values=col_qual)+
      scale_x_discrete(labels=scale.manual.lab)+
      labs(title = title.lab,
           subtitle = subtitle.lab)

    pdf(file=filePlotOut,width=pdf.width,height = pdf.height)
    print(gg)
    dev.off( )
  }
}
